site_name: IS_Bot 文档
site_description: IS_Bot机器人项目的详细文档
site_author: ZMAI
site_url: https://fennmai.github.io/IS_Bot/

# 指定Markdown源文件目录
docs_dir: docs_src
# 指定生成的网站目录(github pages -> 指定为 main -> docs)
site_dir: docs

theme:
  name: material
  language: zh
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - 首页: index.md
  - 项目概述: overview.md
  - 技术架构:
    - 系统架构: architecture/system.md
    - 仿真环境(Mujoco): architecture/mujoco_env.md
    - 真实环境: architecture/real_env.md
    - 遥操作: architecture/teleop.md
  - 文件结构:
    - 项目结构总览: file_structure/overview.md
    - 核心模块: file_structure/core_modules.md
    - 物理模拟: file_structure/simulation.md
    - 机器人控制: file_structure/robot_control.md
  - 使用教程:
    - 环境配置: tutorials/setup.md
    - 基本操作: 
        - 概述: tutorials/basic_usage.md
        - 仿真启动: tutorials/mujoco_usage.md
        - 真机启动: tutorials/real_robot_usage.md
        - 遥操作启动: tutorials/teleop.md
    - 高级操作: 
        - 概述: tutorials/advanced_features.md
        - 数据回放: tutorials/data_replay.md
        - 数据增强: tutorials/data_augmentation.md
        - 数据集管理与转换: tutorials/dataset_management.md
        - 模型部署: tutorials/model_deployment.md
    - 历史笔记:
        - 20250321_notes: tutorials/20250321_notes.md
        - 20250420_notes: tutorials/20250420_notes.md
    - 未来规划:
        - 拓展接口功能: tutorials/extend_interface.md
  - API参考:
    - MujocoEnv: api/mujoco_env.md
    - 机器人控制器: api/controllers.md
  - 文档更新与贡献指南: contributing.md



